In [1]:
import numpy as np
import pandas as pd
from pandas_datareader import data as wb

In [2]:
# This function returns dataFrame based on the ticker, source and start date sent in
def getDataFrame(ticker, source, start = None):
    if start is not None:
        return wb.DataReader(ticker, data_source = source , start = start)
    
    #This else if retrieves data from alpha-vantage using timeSeries
    elif source == 'alpha-vantage' and start == None:
        from alpha_vantage.timeseries import TimeSeries
        ts = TimeSeries(key = 'R55PSMFBEK16QI1C', output_format = 'pandas')
        AAPL_av, metadata = ts.get_daily_adjusted(ticker, outputsize = 'full')
        return AAPL_av
    
    # Return Error
    else:
        raise ValueError("Invalid Input")
        return -1

# Function should be called in the format: getTheDataFrame('AAPL', 'yahoo', '2015-01-01')

In [3]:
getDataFrame('AAPL', 'yahoo', '2015-01-01')

,High,Low,Open,Close,Volume,Adj Close
Date,,,,,,
2015-01-02,111.440002,107.349998,111.389999,109.330002,53204600.0,101.963631
2015-01-05,108.650002,105.410004,108.290001,106.250000,64285500.0,99.091148
2015-01-06,107.430000,104.629997,106.540001,106.260002,65797100.0,99.100471
2015-01-07,108.199997,106.699997,107.199997,107.750000,40105900.0,100.490089
2015-01-08,112.150002,108.699997,109.230003,111.889999,59364500.0,104.351151
2015-01-09,113.250000,110.209999,112.669998,112.010002,53699500.0,104.463051
2015-01-12,112.629997,108.800003,112.599998,109.250000,49650800.0,101.889015
2015-01-13,112.800003,108.910004,111.430000,110.220001,67091900.0,102.793655
2015-01-14,110.489998,108.500000,109.040001,109.800003,48337000.0,102.401962
2015-01-15,110.059998,106.660004,110.000000,106.820000,60014000.0,99.622726
2015-01-16,107.580002,105.199997,107.029999,105.989998,78513300.0,98.848663
2015-01-20,108.970001,106.500000,107.839996,108.720001,49899900.0,101.394730
2015-01-21,111.059998,108.269997,108.949997,109.550003,48575900.0,102.168816
2015-01-22,112.470001,109.720001,110.260002,112.400002,53796400.0,104.826790
2015-01-23,113.750000,111.529999,112.300003,112.980003,46464800.0,105.367699
2015-01-26,114.360001,112.800003,113.739998,113.099998,55615000.0,105.479630
2015-01-27,112.480003,109.029999,112.419998,109.139999,95568700.0,101.786430
2015-01-28,118.120003,115.309998,117.629997,115.309998,146477100.0,107.540718
2015-01-29,119.190002,115.559998,116.320000,118.900002,84436400.0,110.888824
2015-01-30,120.000000,116.849998,118.400002,117.160004,83745500.0,109.266068
2015-02-02,119.169998,116.080002,118.050003,118.629997,62739100.0,110.637016
2015-02-03,119.089996,117.610001,118.500000,118.650002,51915700.0,110.655670
2015-02-04,120.510002,118.309998,118.500000,119.559998,70149700.0,111.504333
2015-02-05,120.230003,119.250000,120.019997,119.940002,42246200.0,112.300217
2015-02-06,120.250000,118.449997,120.019997,118.930000,43706600.0,111.354553
2015-02-09,119.839996,118.430000,118.550003,119.720001,38889800.0,112.094223
2015-02-10,122.150002,120.160004,120.169998,122.019997,62008500.0,114.247726
2015-02-11,124.919998,122.500000,122.769997,124.879997,73561800.0,116.925545
2015-02-12,127.480003,125.570000,126.059998,126.459999,74474500.0,118.404915
2015-02-13,127.279999,125.650002,127.279999,127.080002,54272200.0,118.985435
...,...,...,...,...,...,...
2018-11-19,190.699997,184.990005,190.000000,185.860001,41925300.0,185.860001
2018-11-20,181.470001,175.509995,178.369995,176.979996,67825200.0,176.979996
2018-11-21,180.270004,176.550003,179.729996,176.779999,31124200.0,176.779999
2018-11-23,176.600006,172.100006,174.940002,172.289993,23624000.0,172.289993
2018-11-26,174.949997,170.259995,174.240005,174.619995,44998500.0,174.619995
2018-11-27,174.770004,170.880005,171.509995,174.240005,41387400.0,174.240005
2018-11-28,181.289993,174.929993,176.729996,180.940002,46062500.0,180.940002
2018-11-29,182.800003,177.699997,182.660004,179.550003,41770000.0,179.550003
2018-11-30,180.330002,177.029999,180.289993,178.580002,39531500.0,178.580002
2018-12-03,184.940002,181.210007,184.460007,184.820007,40802500.0,184.820007
2018-12-04,182.389999,176.270004,180.949997,176.690002,41344300.0,176.690002
2018-12-06,174.779999,170.419998,171.759995,174.720001,43098400.0,174.720001
2018-12-07,174.490005,168.300003,173.490005,168.490005,42281600.0,168.490005
2018-12-10,170.089996,163.330002,165.000000,169.600006,62026000.0,169.600006
2018-12-11,171.789993,167.000000,171.660004,168.630005,47281700.0,168.630005
2018-12-12,171.919998,169.020004,170.399994,169.100006,35627700.0,169.100006
2018-12-13,172.570007,169.550003,170.490005,170.949997,31898600.0,170.949997
2018-12-14,169.080002,165.279999,169.000000,165.479996,40703700.0,165.479996
2018-12-17,168.350006,162.729996,165.449997,163.940002,44287900.0,163.940002
2018-12-18,167.529999,164.389999,165.380005,166.070007,33841500.0,166.070007
2018-12-19,167.449997,159.089996,166.000000,160.889999,49047300.0,160.889999
2018-12-20,162.110001,155.300003,160.399994,156.830002,64773000.0,156.830002
2018-12-21,158.160004,149.630005,156.860001,150.729996,95744600.0,150.729996
2018-12-24,151.550003,146.589996,148.149994,146.830002,37169200.0,146.830002
2018-12-26,157.229996,146.720001,148.300003,157.169998,58582500.0,157.169998
2018-12-27,156.770004,150.070007,155.839996,156.149994,53117100.0,156.149994
2018-12-28,158.520004,154.550003,157.500000,156.229996,42291400.0,156.229996
2018-12-31,159.360001,156.479996,158.529999,157.740005,35003500.0,157.740005
2019-01-02,158.850006,154.229996,154.889999,157.919998,36360000.0,157.919998
2019-01-03,145.713699,142.080994,143.979996,143.070007,68340960.0,143.070007

In [4]:
getDataFrame('AAPL', 'alpha-vantage')

,1. open,2. high,3. low,4. close,5. adjusted close,6. volume,7. dividend amount,8. split coefficient
date,,,,,,,,
1998-01-02,13.63,16.2500,13.500,16.25,0.5125,6411700.0,0.0,1.0
1998-01-05,16.50,16.5600,15.190,15.88,0.5009,5820300.0,0.0,1.0
1998-01-06,15.94,20.0000,14.750,18.94,0.5974,16182800.0,0.0,1.0
1998-01-07,18.81,19.0000,17.310,17.50,0.5519,9300200.0,0.0,1.0
1998-01-08,17.44,18.6200,16.940,18.19,0.5737,6910900.0,0.0,1.0
1998-01-09,18.12,19.3700,17.500,18.19,0.5737,7915600.0,0.0,1.0
1998-01-12,17.44,18.6200,17.120,18.25,0.5756,4610700.0,0.0,1.0
1998-01-13,18.62,19.6200,18.500,19.50,0.6150,5686200.0,0.0,1.0
1998-01-14,19.87,19.9400,19.250,19.75,0.6229,5261300.0,0.0,1.0
1998-01-15,19.19,19.7500,18.620,19.19,0.6053,4993500.0,0.0,1.0
1998-01-16,19.44,19.4400,18.690,18.81,0.5933,2199600.0,0.0,1.0
1998-01-20,19.06,19.3100,18.620,19.06,0.6012,2156800.0,0.0,1.0
1998-01-21,18.75,19.0600,18.560,18.91,0.5964,1698300.0,0.0,1.0
1998-01-22,18.69,19.7500,18.620,19.25,0.6071,2944000.0,0.0,1.0
1998-01-23,19.37,19.6900,19.250,19.50,0.6150,2081800.0,0.0,1.0
1998-01-26,19.44,19.5600,18.810,19.44,0.6131,1307500.0,0.0,1.0
1998-01-27,19.19,19.6900,19.000,19.12,0.6030,1002100.0,0.0,1.0
1998-01-28,19.19,19.3700,18.620,19.19,0.6053,1349300.0,0.0,1.0
1998-01-29,18.94,19.1200,18.500,18.50,0.5835,1891800.0,0.0,1.0
1998-01-30,18.31,18.8700,18.250,18.31,0.5775,1450400.0,0.0,1.0
1998-02-02,18.50,18.5000,17.370,17.69,0.5579,5685200.0,0.0,1.0
1998-02-03,17.69,18.6200,17.690,18.31,0.5775,3594800.0,0.0,1.0
1998-02-04,18.06,18.5000,18.000,18.25,0.5756,1519600.0,0.0,1.0
1998-02-05,18.25,18.5000,18.000,18.31,0.5775,2127400.0,0.0,1.0
1998-02-06,18.37,18.6900,18.250,18.50,0.5835,1806600.0,0.0,1.0
1998-02-09,18.37,19.5000,18.370,19.19,0.6053,4416700.0,0.0,1.0
1998-02-10,19.12,19.5600,19.060,19.44,0.6131,3768000.0,0.0,1.0
1998-02-11,19.50,19.5000,18.870,19.00,0.5993,1889900.0,0.0,1.0
1998-02-12,19.12,19.4400,19.060,19.37,0.6109,1819200.0,0.0,1.0
1998-02-13,19.19,19.8700,19.000,19.50,0.6150,1857100.0,0.0,1.0
...,...,...,...,...,...,...,...,...
2018-11-19,190.00,190.7000,184.990,185.86,185.8600,41920872.0,0.0,1.0
2018-11-20,178.37,181.4700,175.510,176.98,176.9800,67825247.0,0.0,1.0
2018-11-21,179.73,180.2700,176.550,176.78,176.7800,31124210.0,0.0,1.0
2018-11-23,174.94,176.5950,172.100,172.29,172.2900,23623972.0,0.0,1.0
2018-11-26,174.24,174.9500,170.260,174.62,174.6200,44998520.0,0.0,1.0
2018-11-27,171.51,174.7700,170.880,174.24,174.2400,41387377.0,0.0,1.0
2018-11-28,176.73,181.2900,174.930,180.94,180.9400,46062539.0,0.0,1.0
2018-11-29,182.66,182.8000,177.700,179.55,179.5500,41769992.0,0.0,1.0
2018-11-30,180.29,180.3300,177.030,178.58,178.5800,39531549.0,0.0,1.0
2018-12-03,184.46,184.9400,181.210,184.82,184.8200,40798002.0,0.0,1.0
2018-12-04,180.95,182.3899,176.270,176.69,176.6900,41344282.0,0.0,1.0
2018-12-06,171.76,174.7800,170.420,174.72,174.7200,43098410.0,0.0,1.0
2018-12-07,173.49,174.4900,168.300,168.49,168.4900,42281631.0,0.0,1.0
2018-12-10,165.00,170.0900,163.330,169.60,169.6000,62025994.0,0.0,1.0
2018-12-11,171.66,171.7900,167.000,168.63,168.6300,47281665.0,0.0,1.0
2018-12-12,170.40,171.9200,169.020,169.10,169.1000,35627674.0,0.0,1.0
2018-12-13,170.49,172.5700,169.550,170.95,170.9500,31897827.0,0.0,1.0
2018-12-14,169.00,169.0800,165.280,165.48,165.4800,40703710.0,0.0,1.0
2018-12-17,165.45,168.3500,162.730,163.94,163.9400,44287922.0,0.0,1.0
2018-12-18,165.38,167.5300,164.390,166.07,166.0700,33841518.0,0.0,1.0
2018-12-19,166.00,167.4500,159.090,160.89,160.8900,49047297.0,0.0,1.0
2018-12-20,160.40,162.1100,155.300,156.83,156.8300,64772960.0,0.0,1.0
2018-12-21,156.86,158.1600,149.630,150.73,150.7300,95744384.0,0.0,1.0
2018-12-24,148.15,151.5500,146.590,146.83,146.8300,37169232.0,0.0,1.0
2018-12-26,148.30,157.2300,146.720,157.17,157.1700,58582544.0,0.0,1.0
2018-12-27,155.84,156.7700,150.070,156.15,156.1500,53117065.0,0.0,1.0
2018-12-28,157.50,158.5200,154.550,156.23,156.2300,42291424.0,0.0,1.0
2018-12-31,158.53,159.3600,156.480,157.74,157.7400,35003466.0,0.0,1.0
2019-01-02,154.89,158.8500,154.230,157.92,157.9200,37039737.0,0.0,1.0
2019-01-03,143.98,145.7137,142.081,143.06,143.0600,68341060.0,0.0,1.0